name: Publish API server image to GHCR and Deploy to K8s using ArgoCD

on:
  push:
    branches: [main]
    paths:
      - 'api-server/**'
  release:
    types: [published]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/exosphere-api-server
  SHA_TAG: ${{ github.sha }}
  APP_NAME: exosphere-api-server

jobs:
  publish-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate tags & labels
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw, value=latest
            type=sha, value=${{ env.SHA_TAG }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./api-server
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy-to-k8s:
    needs: publish-image
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to K8s
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > kubeconfig.yaml
          export KUBECONFIG=$PWD/kubeconfig.yaml
          kubectl get nodes

          kubectl set image deployment/exosphere-api-server app=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.SHA_TAG }}

          kubectl rollout status deployment/exosphere-api-server --timeout=1200s

          status=$(kubectl rollout status deployment/exosphere-api-server --watch false)

          echo "$status"

          if [[ "$status" != *"successfully rolled out"* ]]; then
            kubectl rollout undo deployment/exosphere-api-server -n your-namespace
            echo "âŒ Deployment failed. Rolled back." >&2
            exit 1
          fi